# Project Information
site_name: Android Study Notes
site_author: WOC-BUG

# Repository
repo_name: 'WOC-BUG/Android-Study-Notes'
repo_url: https://github.com/WOC-BUG/Android-Study-Notes

# Table of Contents
nav:
    - 简介:
      - 首页: index.md
    - Java:
      - Head First Java: Head First Java.md
      - Java基础: Java基础.md
    - kotlin:
      - kotlin学习笔记: kotlin学习笔记.md
    - Android:
      - Android基础: Android基础.md
      - BLE低功耗蓝牙通信: BLE低功耗蓝牙通信.md
    - Flutter:
      - Flutter调研报告: Flutter.md
      - Dart语言基础: Dart.md
    - Design Pattern:
      - 大话设计模式: 大话设计模式.md
    - 实践:
      - 工作问题记录: 工作问题记录.md

# Theme
theme:
    name: lux

# Extensions
markdown_extensions:
    - admonition
    - toc:
        permalink: '#'

plugins:
    - search