# Project Information
site_name: Android Study Notes
site_author: WOC-BUG

# Repository
repo_name: 'WOC-BUG/Android-Study-Notes'
repo_url: https://github.com/WOC-BUG/Android-Study-Notes

# Table of Contents
nav:
    - 简介:
      - 首页: index.md
    - kotlin:
      - kotlin学习笔记: kotlin学习笔记.md
    - Android:
      - Android基础: Android基础.md
      - BLE低功耗蓝牙通信: BLE低功耗蓝牙通信.md

# Theme
theme: readthedocs
