name: Android Study Notes

on:
    push

jobs:
    my-first-job:
        runs-on: ubuntu-20.04
        steps:
          - name: Check out Git repostory
            uses: actions/checkout@v2
          - name: Deploy to Github Pages
            uses: WOC-BUG/mkdocs-deploy-gh-pages@master
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REQUIREMENTS: requirements.txt