name: Android Study Notes

on:
    push

jobs:
    my-first-job:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/woc-bug@master
          - name: Deploy to Github Pages
            uses: woc-bug/mkdocs-deploy-gh-pages@master
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REQUIREMENTS: requirements.txt