name: Android Study Notes

on:
    push

jobs:
    my-first-job:
        runs-on: ubuntu-20.04
        steps:
          - name: Check out Git repostory
            uses: actions/checkout@v2
          - name: Deploy MkDocs
            uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REQUIREMENTS: requirements.txt